In [2]:
import numpy as np

In [4]:
li1 = [1, 2, 3]
print('li1: ', li1)
print('li1 type: ', type(li1))

arr1 = np.array(li1)
print("arr1: ", arr1)
print('arr1 type: ', type(arr1))

li1:  [1, 2, 3]
li1 type:  <class 'list'>
arr1:  [1 2 3]
arr1 type:  <class 'numpy.ndarray'>


In [18]:
arr1 = np.array([1,2,3])
print('arr1 type: ', type(arr1))
print('arr1 arr형태: ', arr1.shape)

arr2 = np.array([[1,2,3], [2,3,4]])
print('arr2 type: ', type(arr2))
print('arr2 arr형태: ', arr2.shape)

# arr1과 다름 주의(대괄호로 한 겹 더 묶여있음)
arr3 = np.array([[1,2,3]])
print('arr3 type: ', type(arr3))
print('arr3 arr형태: ', arr3.shape)

arr1 type:  <class 'numpy.ndarray'>
arr1 arr형태:  (3,)
arr2 type:  <class 'numpy.ndarray'>
arr2 arr형태:  (2, 3)
arr3 type:  <class 'numpy.ndarray'>
arr3 arr형태:  (1, 3)


- ndim

In [17]:
print('arr1: {0}차원, arr2: {1}차원, arr3: {2}차원'.format(arr1.ndim, arr2.ndim, arr3.ndim))

arr1: 1차원, arr2: 2차원, arr3: 2차원


- dtype()

In [21]:
li = [1,2, 3]
print(type(li))
arr1 = np.array(li1)

print(type(arr1))
print(arr1, arr1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


#### 자료형이 섞인 리스트를 ndarray로 변환할 경우 크기가 더 큰 datatype으로 통일

In [20]:
li2 = [1, 2, 'test']
arr2 = np.array(li2)
print(arr2, arr2.dtype)

li3 = [1, 2, 3.0]
arr3 = np.array(li3)
print(arr3, arr3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


#### astype() : data type 변환

In [22]:
arr = np.array([1.0, 2.1, 3,3])
arr = arr.astype('int32')
print(arr, arr.dtype)

[1 2 3 3] int32


#### axis - 0: 행 방향, 1: 열 방향

In [23]:
arr = np.array([[1,2,3], [4,5,6]])
print('전체 합: ', arr.sum())
print('sum of axis0: ', arr.sum(axis=0))
print('sum of axis1: ', arr.sum(axis=1))

전체 합:  21
sum of axis0:  [5 7 9]
sum of axis1:  [ 6 15]
