In [3]:
import numpy as np

#### 행렬의 정렬 - sort() & argsort()

In [3]:
org_array = np.array([3, 1, 9, 5])
print('원본: ', org_array)
print()

# np.sort()
sort_array1 = np.sort(org_array)
print('sort_array1: ', sort_array1)
print('org_array: ', org_array)
print()

# ndarray.sort()
sort_array2 = org_array.sort()
print('sort_array2: ', sort_array2)
print('org_array: ', org_array)


원본:  [3 1 9 5]

sort_array1:  [1 3 5 9]
org_array:  [3 1 9 5]

sort_array2:  None
org_array:  [1 3 5 9]


#### 내림차순 정렬

In [5]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순 정렬: ', sort_array1_desc)

내림차순 정렬:  [9 5 3 1]


#### Axis 방향에 따른 정렬

In [7]:
array2d = np.array([[8, 12],
                  [7, 1]])
print('array2d:\n', array2d)
print()

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향 정렬:\n', sort_array2d_axis0)
print()

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향 정렬:\n', sort_array2d_axis1)


array2d:
 [[ 8 12]
 [ 7  1]]

로우 방향 정렬:
 [[ 7  1]
 [ 8 12]]

컬럼 방향 정렬:
 [[ 8 12]
 [ 1  7]]


#### argsort

In [9]:
org_array = np.array([3, 1, 9, 5])
print(np.sort(org_array))
print()

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('원본 행렬 인덱스: ', sort_indices)

[1 3 5 9]

<class 'numpy.ndarray'>
원본 행렬 인덱스:  [1 0 3 2]


In [10]:
org_array = np.array([3, 1, 9, 5])
print(np.sort(org_array)[::-1])
print()

sort_indices_desc = np.argsort(org_array)[::-1]
print('내림차순 행렬 정렬 후 원본 행렬 인덱스: ', sort_indices_desc)

[9 5 3 1]

내림차순 행렬 정렬 후 원본 행렬 인덱스:  [2 3 0 1]


#### 활용 예시 - 점수 순으로 이름 정렬

In [11]:
name = np.array(['Kim', 'Jon', 'Lee', 'Choi', 'Park'])
score = np.array([23, 40, 10, 22, 5])

sort_indices = np.argsort(score)
print("sort indices: ", sort_indices)
print()

name_sort = name[sort_indices]
score_sort = score[sort_indices]
print(name_sort)
print(score_sort)

sort indices:  [4 2 3 0 1]

['Park' 'Lee' 'Choi' 'Kim' 'Jon']
[ 5 10 22 23 40]


#### 선형대수 - 내적과 전치 행렬

In [12]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[7, 8],
             [9, 10],
             [11, 12]])

dot_product = np.dot(a, b)
print('내적: \n', dot_product)

내적: 
 [[ 58  64]
 [139 154]]


In [4]:
c = np.array([[1,2],
            [3,4]])
transpose_mat = np.transpose(c)
print('전치 행렬: \n', transpose_mat)

전치 행렬: 
 [[1 3]
 [2 4]]


In [16]:
d = np.arange(9)
d = d.reshape(3,3)
print('d: \n', d)
print()
transpose_mat = np.transpose(d)
print('전치 행렬: \n', transpose_mat)

d: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

전치 행렬: 
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
