In [16]:
import numpy as np

#### zeros, ones

In [17]:
zero_arr = np.zeros((3,2),dtype='int32')
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape)

one_arr = np.ones((3,2))
print(one_arr)
print(one_arr.dtype, one_arr.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#### reshape

In [15]:
arr1 = np.arange(10)
print('arr1: \n', arr1)

arr2 = arr1.reshape(2, 5)
print('arr2: \n', arr2)

arr3 = arr2.reshape(5, 2)
print('arr3: \n', arr3)

arr1: 
 [0 1 2 3 4 5 6 7 8 9]
arr2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#### reshape: -1을 인자로 줬을 때 가변적으로 변환

In [19]:
arr1 = np.arange(10)
print(arr1)

arr2 = arr1.reshape(-1, 5)
print('arr2 shape:', arr2.shape)
print('arr2:\n', arr2)

arr3 = arr1.reshape(5, -1)
print('arr3 shape: ', arr3.shape)
print('arr3:\n', arr3)

[0 1 2 3 4 5 6 7 8 9]
arr2 shape: (2, 5)
arr2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr3 shape:  (5, 2)
arr3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#### reshape: 인자 하나를 비웠을 때 차이

In [21]:
arr1 = np.arange(5)

# 1차원 ndarray를 2차원으로 변환하되, 컬럼axis크기는 1이됨
arr2d_1 = arr1.reshape(-1, 1)
print("arr2d_1 shape: ", arr2d_1.shape)
print("arr2d_1:\n", arr2d_1)

# 2d ndarray를 1차원으로 변환
arr1d = arr2d_1.reshape(-1, )
print("arr1d shape: ", arr1d.shape)
print("arr1d: \n", arr1d)

arr2d_1 shape:  (5, 1)
arr2d_1:
 [[0]
 [1]
 [2]
 [3]
 [4]]
arr1d shape:  (5,)
arr1d: 
 [0 1 2 3 4]


#### reshape의 인자값으로 -1은 두개 이상 사용 불가능